version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-container
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - app-network

  backend:
    build: .
    container_name: first_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:admin@postgres:5432/postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
